export function generateInstructions(screens, connections) {
  let output = `# Mobile App Flow — AI Build Instructions\n`;
  output += `# Generated by FlowForge\n`;
  output += `# Total Screens: ${screens.length} | Total Connections: ${connections.length}\n\n`;
  output += `---\n\n`;

  output += `## SCREENS\n\n`;
  screens.forEach((s, i) => {
    output += `### Screen ${i + 1}: "${s.name}"\n`;
    output += `  - ID: ${s.id}\n`;
    output += `  - Has Design Image: ${s.imageData ? "YES (refer to attached screen capture/wireframe)" : "NO — needs design"}\n`;
    if (s.description) output += `  - Description: ${s.description}\n`;
    output += `  - Canvas Position: (${Math.round(s.x)}, ${Math.round(s.y)})\n`;

    if (s.hotspots.length > 0) {
      output += `  - Interactive Elements:\n`;
      s.hotspots.forEach((h, j) => {
        output += `      ${j + 1}. "${h.label || "Unnamed tap area"}"\n`;
        output += `         - Position: (x:${h.x}%, y:${h.y}%, w:${h.w}%, h:${h.h}%)\n`;
        output += `         - Action: ${h.action}\n`;
        if (h.targetScreenId) {
          const target = screens.find((ts) => ts.id === h.targetScreenId);
          output += `         - Target: "${target?.name || "Unknown"}" (${h.targetScreenId})\n`;
        }
      });
    } else {
      output += `  - Interactive Elements: None defined\n`;
    }
    output += `\n`;
  });

  output += `## NAVIGATION FLOW\n\n`;
  if (connections.length === 0) {
    output += `No connections defined yet.\n\n`;
  } else {
    connections.forEach((c, i) => {
      const from = screens.find((s) => s.id === c.fromScreenId);
      const to = screens.find((s) => s.id === c.toScreenId);
      output += `${i + 1}. "${from?.name}" → "${to?.name}"`;
      if (c.label) output += ` [trigger: "${c.label}"]`;
      if (c.action) output += ` (${c.action})`;
      output += `\n`;
    });
    output += `\n`;
  }

  output += `## BUILD INSTRUCTIONS FOR AI\n\n`;
  output += `1. Create a mobile app (React Native / Flutter / SwiftUI — choose based on project needs)\n`;
  output += `2. Implement each screen listed above as a separate component/view\n`;
  output += `3. Replicate the visual design from each screen's attached image/wireframe as closely as possible\n`;
  output += `4. Wire up all navigation flows exactly as described in the NAVIGATION FLOW section\n`;
  output += `5. For each interactive element, implement the specified action type:\n`;
  output += `   - "navigate" → Push/navigate to the target screen\n`;
  output += `   - "back" → Pop/go back to previous screen\n`;
  output += `   - "modal" → Present target screen as a modal/overlay\n`;
  output += `   - "api" → Placeholder for API integration (add TODO comment)\n`;
  output += `   - "custom" → Placeholder for custom logic (add TODO comment)\n`;
  output += `6. Set up proper navigation stack/router with all routes\n`;
  output += `7. Add smooth transitions between screens matching mobile platform conventions\n`;
  output += `8. Ensure responsive layout that adapts to different screen sizes\n\n`;

  output += `## SCREEN REFERENCE IMAGES\n\n`;
  output += `The following screens have design reference images attached. `;
  output += `Implement the UI to match these designs as closely as possible:\n\n`;
  screens.forEach((s, i) => {
    if (s.imageData) {
      output += `- Screen ${i + 1} ("${s.name}"): [Image attached — see artifact/wireframe]\n`;
    }
  });

  return output;
}
